FROM mstorsjo/llvm-mingw:20200325

# The gdk-pixbuf build requires the glib-genmarshal tool (libglib2.0-dev-bin)
# Not sure how close the native glib version must be to the one we're cross compiling.
# gtk requires glib-compile-schemas (libglib2.0-bin) and gdk-pixbuf-pixdata (libgdk-pixbuf2.0-dev).

RUN apt-get update && \
    apt-get install -y --no-install-recommends gperf help2man python3-pip python3-setuptools libglib2.0-dev-bin libglib2.0-bin libgdk-pixbuf2.0-dev zip nasm libtool-bin && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install meson==0.54.0

ENV ARCH=aarch64

